import './style.css';
import './illustration.css';
import { act, canFinishCampaign, chooseTool, newRun, tools, type Resource, type ToolId } from './engine';

type Save = { owned: ToolId[]; run: Resource; settings: { motion: boolean; sound: boolean }; resetReady: boolean; complete: boolean };
const realKey = 'finite-forge:v1';
const demoKey = 'demo:finite-forge:v1';
let demo = location.pathname === '/demo' || new URLSearchParams(location.search).get('demo') === '1';
let save: Save;
let notice = '';
let license = false;
let licenseNote = '';
const app = document.querySelector<HTMLDivElement>('#app')!;

function fresh(): Save { return { owned: [], run: newRun([]), settings: { motion: true, sound: false }, resetReady: false, complete: false }; }
function load() { try { const key = demo ? demoKey : realKey; const raw = localStorage.getItem(key); const parsed = JSON.parse(raw || 'null'); save = parsed?.run ? parsed : fresh(); if (!raw) localStorage.setItem(key, JSON.stringify(save)); } catch { save = fresh(); notice = 'Saved progress could not be read. A new forge plan is ready.'; } }
function persist() { localStorage.setItem(demo ? demoKey : realKey, JSON.stringify(save)); }
function setTitle(title: string) { document.title = title; }
function route() { return location.pathname; }
function nav(path: string) { history.pushState({}, '', path); render(); }
window.addEventListener('popstate', render);

async function verifyLicense(token: string) {
  const cacheKey = 'sb_license_check:finite-forge'; const cached = localStorage.getItem(cacheKey);
  if (cached) { const c = JSON.parse(cached); if (Date.now() - c.time < 86400000) { license = c.valid; return; } }
  try { const r = await fetch(`https://api.sociobot.in/api/v1/products/finite-forge/verify?license=${encodeURIComponent(token)}`); const data = await r.json(); license = data.valid === true; localStorage.setItem(cacheKey, JSON.stringify({ valid: license, time: Date.now() })); if (!license) licenseNote = 'This license is no longer active.'; render(); } catch { license = true; }
}
function initLicense() {
  const q = new URLSearchParams(location.search); const token = q.get('license');
  if (token) { localStorage.setItem('sb_license:finite-forge', token); q.delete('license'); history.replaceState({}, '', `${location.pathname}${q.size ? `?${q}` : ''}`); license = true; void verifyLicense(token); }
  else { const stored = localStorage.getItem('sb_license:finite-forge'); if (stored) { license = true; void verifyLicense(stored); } }
}
function action(kind: 'mine'|'shape'|'charge') { save.run = act(save.run, kind, save.owned); if (save.run.completed) { save.resetReady = true; notice = 'Beacon charged. Choose one tool for your next plan.'; } if (save.run.failed) notice = 'Sunset arrived. Reset and keep your planned tool.'; persist(); render(); }
function resetRun() { if (!save.resetReady && !save.run.failed) return; if (!license && save.owned.length >= 1) { notice = 'The free forge includes the first reset. The full campaign needs a license.'; render(); return; } const t = chooseTool(save.owned); if (t) save.owned.push(t); if (canFinishCampaign(save.owned) && save.run.completed) save.complete = true; else { save.run = newRun(save.owned); save.resetReady = false; } persist(); render(); }
function resetDemo() { localStorage.removeItem(demoKey); save = fresh(); notice = 'Sample forge reset.'; render(); }
function startReal() { localStorage.removeItem(demoKey); demo = false; nav('/'); }
function restoreLicense(form: HTMLFormElement) { const input = form.querySelector<HTMLInputElement>('input')!; const t = input.value.trim(); if (!t) return; localStorage.setItem('sb_license:finite-forge', t); license = true; licenseNote = ''; void verifyLicense(t); input.value=''; render(); }
function prettyTool(t: ToolId) { return `<li><strong>${tools[t].name}</strong><span>${tools[t].note}</span></li>`; }
function header() { return `<header><a class="wordmark" href="/" data-link>FINITE<br><b>FORGE</b></a><nav aria-label="Primary"><a href="/demo" data-link>Demo</a><a href="/#how" data-link>How it works</a><a href="/privacy" data-link>Privacy</a></nav></header>`; }
function footer() { return `<footer><p>A finite browser forge for one evening.</p><p><a href="/privacy" data-link>Privacy</a> · <a href="/terms" data-link>Terms</a> · Built by Param Factory · v1.0.0</p><p>Blueprint illustration uses original generated imagery.</p></footer>`; }
function demoBanner() { return demo ? `<aside class="demo" role="status"><b>Demo — sample data, nothing is saved</b><button data-reset-demo>Reset demo</button><button data-start-real>Start for real</button></aside>` : ''; }
function game() {
 const s=save.run; const goal=6; const left=Math.max(0,s.deadline-s.tick); const status=s.completed?'Beacon ready':s.failed?'Sunset reached':`${left} ticks before sunset`;
 const locked=save.complete ? 'complete' : s.completed||s.failed ? 'between' : '';
 return `<section class="game-shell ${locked}" aria-label="Forge board"><div class="board-title"><p>RUN ${String(save.owned.length+1).padStart(2,'0')} · ${status}</p><button class="quiet" data-settings aria-expanded="false">Settings</button></div>
 <div class="blueprint" aria-label="Production blueprint"><div class="station ore"><span>01</span><b>ORE</b><em>${s.ore}</em></div><div class="line"></div><div class="station parts"><span>02</span><b>PARTS</b><em>${s.parts}</em></div><div class="line"></div><div class="station charge"><span>03</span><b>CHARGE</b><em>${Math.min(s.charge,goal)}/${goal}</em></div><div class="beacon ${s.completed?'lit':''}" aria-label="Beacon ${s.completed?'charged':'unlit'}"><i></i><b>BEACON</b></div></div>
 <div class="controls" aria-label="Production controls"><button data-action="mine" ${locked?'disabled':''}><kbd>M</kbd> Mine ore <small>+${save.owned.includes('bellows')?2:1}</small></button><button data-action="shape" ${locked?'disabled':''}><kbd>S</kbd> Shape parts <small>ore → +${save.owned.includes('pattern')?2:1}</small></button><button data-action="charge" ${locked?'disabled':''}><kbd>C</kbd> Charge beacon <small>part → +${save.owned.includes('lens')?2:1}</small></button></div>
 <p class="tickline"><b>${s.tick}</b> / ${s.deadline} production ticks used. Each action takes one tick.</p>
 ${s.completed||s.failed ? endPanel() : ''}<div class="settings" hidden><label><input type="checkbox" data-motion ${save.settings.motion?'checked':''}> Show board motion</label><label><input type="checkbox" data-sound ${save.settings.sound?'checked':''}> Enable sound cues</label></div></section>`;
}
function endPanel() { if (save.complete) return `<section class="end-panel"><h2>Final beacon lit</h2><p>You completed five forge plans. This campaign ends here.</p><button data-new-campaign>Start a new campaign</button></section>`; const t=chooseTool(save.owned); return `<section class="end-panel"><h2>${save.run.completed?'Reset with one new tool':'Revise this plan'}</h2><p>${save.run.completed&&t?`Your next plan adds ${tools[t].name}: ${tools[t].note}`:'Start the same plan again. Your tools stay marked.'}</p><button class="primary" data-reset>${save.run.completed?'Reset the forge':'Try this plan again'}</button>${!license&&save.owned.length>=1?`<a class="buy" href="https://api.sociobot.in/api/v1/products/finite-forge/checkout">Buy the full campaign for $5</a>`:''}</section>`; }
function home() { setTitle('Finite Forge — Plan short forge runs'); return `${header()}${demoBanner()}<main id="main" tabindex="-1"><section class="intro"><div><p class="eyebrow">A finite incremental game</p><h1>Build a beacon before sunset.</h1><p class="lede">For reset fans who want one complete campaign on a phone.</p><div class="hero-actions"><button class="primary" data-demo>Try it with sample data</button><span>Loads a planned forge run.</span></div><ul class="facts"><li>24 visible production ticks</li><li>Progress stays in this browser</li><li>First run is free</li></ul></div><figure class="hero-art"><img src="/assets/forge-blueprint.webp" width="512" height="768" fetchpriority="high" decoding="async" alt="A blueprint drawing of a small forge connected to a beacon tower."><figcaption>Plan each production tick. The beacon ends the campaign.</figcaption></figure></section>${game()}<section id="how" class="how"><h2>How the forge works</h2><ol><li><b>Make six charges.</b><span>Mine ore, shape parts, then charge the beacon.</span></li><li><b>Reset with one tool.</b><span>A completed plan adds one useful tool.</span></li><li><b>Light the final beacon.</b><span>Four tools complete the campaign.</span></li></ol></section><section class="limits"><h2>What the forge does not do</h2><p>It has no offline income, ads, social pressure, or endless prestige layers. Your progress is stored only in this browser.</p></section><section class="paid"><h2>Full campaign</h2><p>$5 one-time. It adds the plans after your free first reset. No subscription.</p><a class="primary linkbutton" href="https://api.sociobot.in/api/v1/products/finite-forge/checkout">Buy the full campaign</a><form data-restore><label for="license">Have a license? Paste it</label><div><input id="license" name="license" autocomplete="off"><button>Restore purchase</button></div></form>${licenseNote?`<p class="warn">${licenseNote}</p>`:''}</section></main>${footer()}<p class="sr" aria-live="polite">${notice}</p>`; }
function simplePage(kind: 'privacy'|'terms'|'404') { const data = kind==='privacy'?['Privacy — Finite Forge','Privacy','Finite Forge stores your game progress, settings, and optional license token in your browser. It sends no analytics. License verification contacts Sociobot only after you add a license.'] : kind==='terms'?['Terms — Finite Forge','Terms','Finite Forge is a browser game. The $5 full campaign is a one-time license sold by Sociobot, the merchant of record. A refunded license is revoked.'] : ['Not found — Finite Forge','This page is not in the forge.','Return to the forge board to continue your campaign.']; setTitle(data[0]); return `${header()}<main id="main" tabindex="-1" class="document"><h1>${data[1]}</h1><p>${data[2]}</p>${kind==='404'?'<a class="primary linkbutton" href="/" data-link>Return to the forge</a>':''}</main>${footer()}<p class="sr" aria-live="polite">${data[1]}</p>`; }
function wire() { app.querySelectorAll<HTMLAnchorElement>('[data-link]').forEach(a=>a.addEventListener('click', e=>{e.preventDefault(); nav(a.getAttribute('href')!);})); app.querySelector('[data-demo]')?.addEventListener('click',()=>{demo=true; nav('/demo');}); app.querySelectorAll<HTMLButtonElement>('[data-action]').forEach(b=>b.addEventListener('click',()=>action(b.dataset.action as 'mine'|'shape'|'charge'))); app.querySelector('[data-reset]')?.addEventListener('click',resetRun); app.querySelector('[data-reset-demo]')?.addEventListener('click',resetDemo); app.querySelector('[data-start-real]')?.addEventListener('click',startReal); app.querySelector('[data-new-campaign]')?.addEventListener('click',()=>{save=fresh(); persist(); render();}); app.querySelector<HTMLFormElement>('[data-restore]')?.addEventListener('submit',e=>{e.preventDefault();restoreLicense(e.currentTarget as HTMLFormElement)}); const s=app.querySelector<HTMLButtonElement>('[data-settings]'); s?.addEventListener('click',()=>{const pane=app.querySelector<HTMLElement>('.settings')!;pane.hidden=!pane.hidden;s.setAttribute('aria-expanded',String(!pane.hidden));}); app.querySelector<HTMLInputElement>('[data-motion]')?.addEventListener('change',e=>{save.settings.motion=(e.target as HTMLInputElement).checked;persist();}); app.querySelector<HTMLInputElement>('[data-sound]')?.addEventListener('change',e=>{save.settings.sound=(e.target as HTMLInputElement).checked;persist();}); }
function render() { load(); const r=route(); app.innerHTML=r==='/'||r==='/demo'?home():r==='/privacy'?simplePage('privacy'):r==='/terms'?simplePage('terms'):simplePage('404'); wire(); requestAnimationFrame(()=>document.querySelector<HTMLElement>('h1')?.focus({preventScroll:true})); }
window.addEventListener('keydown',e=>{ if ((e.target as HTMLElement).tagName==='INPUT') return; const keys: Record<string,'mine'|'shape'|'charge'>={m:'mine',s:'shape',c:'charge'}; if(keys[e.key.toLowerCase()]&&route().startsWith('/')) { e.preventDefault(); action(keys[e.key.toLowerCase()]); } });
// Fixed 60 Hz visual clock: the simulation itself is turn-based, and this only animates board state.
let last=performance.now(), accumulator=0; function loop(now:number){ const delta=Math.min(250,now-last);last=now;if(!document.hidden){accumulator+=delta;while(accumulator>=1000/60) accumulator-=1000/60;}requestAnimationFrame(loop);} document.addEventListener('visibilitychange',()=>{last=performance.now();}); requestAnimationFrame(loop);
load(); initLicense(); render();
